# Generated by Django 5.2.4 on 2025-08-15 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_user_phone_number_payment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='payment_url',
        ),
        migrations.AddField(
            model_name='booking',
            name='payment_url',
            field=models.URLField(blank=True),
        ),
    ]
